# Alternative GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  BGi_config = debug

else ifeq ($(config),release)
  BGi_config = release

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := BGi

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

BGi:
ifneq (,$(BGi_config))
	@echo "==== Building BGi ($(BGi_config)) ===="
	@${MAKE} --no-print-directory -C . -f BGi.make config=$(BGi_config)
endif

clean:
	@${MAKE} --no-print-directory -C . -f BGi.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   BGi"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"